### ISSUE TITLE
Burp Suite Automation keeps failing while fuzzing

### ISSUE THREAD

**Issue by infa-ritranjan** [justmorpheus/burp-automation#1]
burp suite automation is starting after I'm inputting this command python3 -m robot -d output fuzzing.robot, but the process keeps failing. Could you let me know why?
![Screenshot from 2021-08-18 14-24-44](https://user-images.githubusercontent.com/89129554/129869733-2946c158-7c22-4739-aaba-4ae9ef408faf.png)

**Comment by captainbarber99** [comment]
> burp suite automation is starting after I'm inputting this command python3 -m robot -d output fuzzing.robot, but the process keeps failing. Could you let me know why?
> ![Screenshot from 2021-08-18 14-24-44](https://user-images.githubusercontent.com/89129554/129869733-2946c158-7c22-4739-aaba-4ae9ef408faf.png)

@ritikaranjan15 Did you check the client_secrets.json . 
I think it is missing client_id. The code is running scuccesfully and scan is complete but when python is trying to upload the files into google drive then it is causing issue.
You need to check client_secrets.json. 
Sample is attached.
```{"web":{"client_id":"sddssddsds.apps.googleusercontent.com","project_id":"eng-bloom-12334","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"Idsdddssddsdssd","redirect_uris":["http://localhost:8080/"],"javascript_origins":["http://localhost:8080"]}}```

**Comment by ritikaranjan15** [comment]
If I don't want to upload it on Google Drive, is there a workaround for that?

**Comment by infa-ritranjan** [comment]
![Screenshot from 2021-08-19 18-51-18](https://user-images.githubusercontent.com/89129554/130076000-fb860971-a247-4fb1-aaae-2162ae82f7cb.png)
@justmorpheus Could you help me out with this error? I configured the google drive and client id is added in client secrets json now.

**Comment by captainbarber99** [comment]
@ritikaranjan15 Please remove 
```${GDRIVE}=      upload reports gdrive
    log to console  ${\n}Gdrive Status: ${GDRIVE}"${\n}```
    
    From the fuzzing.robot
    
    Hence the function won't be called.

**Comment by captainbarber99** [comment]
@ritikaranjan15 for generating the keys you can visit official pydrive https://pythonhosted.org/PyDrive/quickstart.html
or
Use https://gist.githubusercontent.com/justmorpheus/3c0f1f1034bc9532afa45fd27fe0dcb4/raw/12ced55441772692960bb9e19de2ccdc73c1910f/oauth-quickstart.py

Run oauth-quickstart.py with client_secrets.json in the same folder. It will generate the correct keys.

Refer: https://infosecwriteups.com/burp-automation-automating-burp-scanning-via-rest-api-robot-framework-using-python3-78aebdd35c53

**Comment by infa-ritranjan** [comment]
> @ritikaranjan15 Please remove
> 
> ```
>     log to console  ${\n}Gdrive Status: ${GDRIVE}"${\n}```
>     
>     From the fuzzing.robot
>     
>     Hence the function won't be called.
> ```

@justm0rph3u5 I did this but it's still failing. Removed the whole log to console line after ${GDRIVE}

**Comment by ritikaranjan15** [comment]
> @ritikaranjan15 for generating the keys you can visit official pydrive https://pythonhosted.org/PyDrive/quickstart.html
> or
> Use https://gist.githubusercontent.com/justmorpheus/3c0f1f1034bc9532afa45fd27fe0dcb4/raw/12ced55441772692960bb9e19de2ccdc73c1910f/oauth-quickstart.py
> 
> Run oauth-quickstart.py with client_secrets.json in the same folder. It will generate the correct keys.
> 
> Refer: https://infosecwriteups.com/burp-automation-automating-burp-scanning-via-rest-api-robot-framework-using-python3-78aebdd35c53

This I have done

**Comment by infa-ritranjan** [comment]
![Screenshot from 2021-08-23 10-13-39](https://user-images.githubusercontent.com/89129554/130391150-798f63f8-e0ff-4e5d-b8aa-f6c9771e8b07.png)
@justm0rph3u5 @justmorpheus I keep getting this error even after altering the fuzzing.robot file as you suggested. What should I do?
